#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Contracts\Console\Kernel as ConsoleKernelContract;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(ConsoleKernelContract::class);

$input = new ArgvInput();
$output = new ConsoleOutput();

$status = $kernel->handle($input, $output);

$kernel->terminate($input, $status);

exit(is_int($status) ? $status : 0);
